services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
        - ./app:/home/hostconf/app:ro
    command: gunicorn -w 2 -b 0.0.0.0:5000 'hostconf:app'
    ports:
      - "5000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.flask.rule=PathPrefix(`/`)"
      - "traefik.http.routers.flask.tls=true"
  proxy:
    image: traefik:v2.10.3
    command:
      - "--log.level=INFO"
      - "--api.insecure=true"
      - "--api.dashboard=false"
      - "--providers.docker.watch=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.file.filename=/conf/traefik.yml"
      - "--providers.file.watch=true"
      - "--entryPoints.web.address=:80"
      - "--entryPoints.websecure.address=:443"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./cert:/cert"
      - "./conf:/conf"
    labels:
      - "traefik.enable=true"

volumes:
  traefik-public-certificates:


