services:
  app:
    build:
      context: .
      dockerfile: docker/Hostconf
    volumes:
        - ./app:/home/hostconf/app:ro
    command: gunicorn -w 2 -b 0.0.0.0:5000 'hostconf:app'
    ports:
      - "5000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.flask.rule=Host(`hostconf.domain.tld`) && PathPrefix(`/`)"
      - "traefik.http.routers.flask.tls=true"
  proxy:
    build:
      context: .
      dockerfile: docker/Traefik
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./cert:/cert"
      - "./conf:/conf"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard.rule=Host(`hostconf.domain.tld`) && PathPrefix(`/dashboard/`)"
      - "traefik.http.routers.dashboard.tls=true"
      - "traefik.http.middlewares.auth.basicauth.users=testuser:$$apr1$$jIKW.bdS$$eKXe4Lxjgy/rH65wP1iQe1"

volumes:
  traefik-public-certificates:


