version: 1
disable_existing_loggers: False
formatters:
  console:
    (): uvicorn.logging.ColourizedFormatter
    fmt: "%(asctime)s %(levelname)s: %(message)s"
    style: "%"
    use_colors: True
handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: console
    stream: ext://sys.stdout
root:
  level: INFO
  handlers: [console]