version: 1
disable_existing_loggers: False
formatters:
  timestamped:
    format: '%(asctime)s - %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: timestamped
    stream: ext://sys.stdout
root:
  level: INFO
  handlers: [console]