tls:
  certificates:
    - certFile: /cert/cert.pem
      keyfile: /cert/key.pem
      stores:
        - default
  stores:
    default:
      defaultCertificate:
        certFile: /cert/cert.pem
        keyfile: /cert/key.pem