services:
  buildenv:
    image: sopra/ipl/pxe-boot:1.0
    volumes:
        - ./output:/root/output:rw
        - ./certs:/etc/ssl/certs:rw
        - ./scripts:/root/scripts:ro
        - ./sbkeys:/root/sbkeys:ro
        - ./conf:/root/conf:ro
    command: /root/scripts/mkstandalone.sh
