services:
  buildenv:
    build: buildenv
    volumes:
        - ./output:/root/output:rw
        - ./scripts:/root/scripts:ro
        - ./sbkeys:/root/sbkeys:ro
        - ./conf:/root/conf:ro
    command: /root/scripts/mkstandalone.sh
