services:
  buildenv:
    image: sopra/ipl/pxe-boot:1.0
    volumes:
        - ./output:/root/output:rw
        - ./certs:/certs:ro
        - ./scripts:/root/scripts:ro
        - ./sbkeys:/root/sbkeys:ro
        - ./conf:/root/conf:ro
    command: /root/scripts/mkstandalone.sh

  test:
    image: tianon/qemu:native-bookworm
    volumes:
        - ./output:/tftp:ro
        - ./test/secureboot:/secureboot:rw
        - ./test/run.sh:/run.sh:ro
        - ./test/iso:/iso:ro
    command: /run.sh
